# Base Local Planner parameters
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
