# Common costmap parameters
obstacle_range: 5.0
raytrace_range: 6.0
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
robot_radius: 0.3

inflation_radius: 0.5
cost_scaling_factor: 5.0

map_type: costmap
observation_sources: laser
laser: {sensor_frame: front_laser, data_type: LaserScan, topic: /p3dx/front_laser/scan, marking: true, clearing: true}
