# Global costmap parameters
global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: false
  width: 50.0
  height: 50.0
  origin_x: -25.0
  origin_y: -25.0
  resolution: 0.1
  transform_tolerance: 1.0

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser
    laser:
      sensor_frame: front_laser
      data_type: LaserScan
      topic: /p3dx/front_laser/scan
      marking: true
      clearing: true
      obstacle_range: 5.0
      raytrace_range: 6.0
